version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db
    networks:
      - app
  web_gin:
    container_name: web_gin
    build: .
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      - app
    depends_on:
      - mongo
networks:
  app:
    driver: bridge
volumes:
  mongo_data:
